config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :products do
    resources :sells
  end
  resources :sells, only: [:new, :create, :index, :show]
  # Defines the root path route ("/")
  root "sells#index"
  resources :pdfgenerator
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  has_and_belongs_to_many :sells, dependent: :destroy 
  validates :name, presence: true
  validates :price, presence: true
  has_one_attached :photo
end

app/models/sell.rb
class Sell < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :products, dependent: :destroy
  validates :total, presence: true
  self.record_timestamps = true
  def total_price
    products.sum(&:price)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :sells, dependent: :destroy
  validates :name, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only:[:show, :edit , :update, :destroy]
  def index
    @products = Product.all
    if params[:query].present?
      @products = @products.where("name ILIKE ?", "%#{params[:query]}%")
    end
  end


  def show
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.save
    if @product.save
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @product.update!(product_params)
    redirect_to @product
  end

  def destroy
    @product.destroy!
    redirect_to products_path, status: :see_other
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price, :photo)
  end

  def set_product
    @product = Product.find(params[:id])
  end
end

app/controllers/sells_controller.rb
class SellsController < ApplicationController
  def index
    @sells = Sell.all
    @total_revenue = calculate_total_revenue(@sells)
    @sell_count = @sells.count
    @most_sold_product = find_most_sold_product(@sells)
  end

  def new
    @sell = Sell.new
    @products = Product.all
  end

  def show
    @sell = Sell.find(params[:id])
  end

def create
  @sell = Sell.new(sell_params)
  @sell.total = calculate_total(@sell.products)

  if @sell.save
    redirect_to sell_path(@sell)
  else
    render 'new'
  end
end

  private

  def sell_params
    params.require(:sell).permit(:product_id, :user_id, product_ids: [])
  end

  def calculate_total(product_ids)
    # Implement your logic to calculate the total based on the product
    # For example, you can sum the prices of selected products
    Product.where(id: product_ids).sum(&:price)
  end

  def calculate_total_revenue(sells)
    sells.sum { |sell| sell.products.sum(&:price) }
  end

  def find_most_sold_product(sells)
    product_counts = Hash.new(0)

    sells.each do |sell|
      sell.products.each do |product|
        product_counts[product] += 1
      end
    end

    most_sold_product = product_counts.max_by { |_product, count| count }

    most_sold_product&.first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pdfgenerator_helper.rb
module PdfgeneratorHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sells_helper.rb
module SellsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LittleBees</title>
    <%= favicon_link_tag "favicon.ico" %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# <%= turbo_include_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://unpkg.com/slim-select@latest/dist/slimselect.css" rel="stylesheet"></link>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>

  <body class="background">
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <script src="https://kit.fontawesome.com/66b41dd09b.js" crossorigin="anonymous"></script>
  </body>
</html>

app/views/products/edit.html.erb
<div class="center-form mt-5">
  <%= simple_form_for @product do |f| %>
      <%= f.input :name, placeholder: "Enter product name"%>
      <%= f.input :description %>
      <%= f.input :price, as: :integer %>
      <%= f.input :photo, as: :file, input_html: { class: "custom-file-input" } %>
    <div class="d-flex justify-content-between align-items-center">
      <%= f.button :submit, class: 'btn btn-success' do %>
        <i class="fas fa-check"></i> Save Changes
      <% end %>
      <%= link_to product_path, class: 'btn btn-warning' do %>
        <i class="fas fa-times"></i> Cancel Edit
      <% end %>
    </div>
  <% end %>
</div>

app/views/products/index.html.erb
<div class="row justify-content-center">
  <div class="col-sm-8 my-3">
    <%= form_with url: products_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Type a keyword"
        %>
      <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
<div class="container d-flex justify-content-between">
  <%= link_to sells_path, class: 'btn btn-secondary mb-2' do %>
    <i class="fas fa-home"></i> Back home
  <% end %>
  <%= link_to new_product_path, class: 'btn btn-success mb-2' do %>
    <i class="fas fa-plus-circle"></i> Add new product
  <% end %>
</div>
<div class="container">
  <h2 class="title">Product list</h2>

<div class="row">
  <% @products.each do |product| %>
    <div class="col-md-4 mb-4">
      <div class="card">
        <%= image_tag product.photo, class: "card-img-top", alt: "Product Image" if product.photo.attached? %>
        <div class="card-body">
          <h2 class="card-title"><%= product.name %></h2>
          <p class="card-text"><%= product.description %></p>
          <h3 class="card-text">$<%= product.price %></h3>
          <%= link_to product, class: 'btn btn-primary' do %>
            <i class="fas fa-info-circle"></i> More details
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

</div>

app/views/products/new.html.erb
<div class="center-form mt-5git a">
<%= simple_form_for @product do |f| %>
  <%= f.input :name, label: "Product Name", placeholder: "Enter product name"%>
  <%= f.input :description %>
  <%= f.input :price, as: :integer%>
  <%= f.input :photo, as: :file, input_html: { class: "custom-file-input" } %>
<div class="button-container">
<%= f.button :submit, "Create Product", class: "btn-success" %>
    <%= link_to '/', class: 'btn btn-secondary mb-2' do %>
      <i class="fas fa-home"></i> Back home
    <% end %>
    <%= link_to products_path, class: 'btn btn-primary mb-2 text-center' do %>
      <i class="fas fa-chevron-left"></i> Back to List
    <% end %>
</div>
<% end %>
</div>

app/views/products/show.html.erb
<div class='container'>
  <%= link_to products_path, class: 'btn btn-primary mb-2 text-center' do %>
    <i class="fas fa-chevron-left"></i> Back to List
  <% end %>
</div>
<div class='container d-flex justify-content-center'>
  <div class="col-md-4 mb-4">
    <div class="card">
      <% if @product.photo.attached? %>
        <%= image_tag @product.photo, class: "card-img-top", alt: "Product Image" %>
      <% else %>
        <p>No Image Available</p>
      <% end %>
      <div class="card-body">
        <h2 class="card-title"><%= @product.name %></h2>
        <p class="card-text"><%= @product.description %></p>
        <h3 class="card-text">$<%= @product.price %></h3>
        <%= link_to edit_product_path, class: 'btn btn-primary' do %>
          <i class="fas fa-edit"></i> Edit
        <% end %>
        <%= link_to @product, class: 'btn btn-danger', data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to permanently delete this product?' } do %>
          <i class="fas fa-trash-alt"></i> Delete
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/sells/index.html.erb
<h2 class='text-center mt-5 mb-4 display-4'>Total Sells Statistics</h>


<div class="container">
  <div class="row justify-content-center">
    <div class="col-xl-6 col-lg-6">
      <div class="card l-bg-orange-dark">
        <div class="card-statistic-3 p-4">
          <div class="card-icon card-icon-large"><i class="fas fa-dollar-sign"></i></div>
          <div class="mb-4">
            <h5 class="card-title mb-0 fw-bolder">Total Revenue</h5>
          </div>
          <div class="row align-items-center mb-2 d-flex">
            <div class="col-8">
              <h2 class="d-flex align-items-center mb-0">
                <p class='fw-bolder'><%= number_to_currency(@total_revenue, unit: '$', precision: 2) %></p>
              </h2>
            </div>
            <div class="col-4 text-right">
              <!-- Additional content if needed -->
            </div>
          </div>
          <div class="progress mt-1 " data-height="8" style="height: 8px;">
            <div class="progress-bar l-bg-cyan" role="progressbar" data-width="25%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100" style="width: 25%;"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<% if @most_sold_product %>
    <h4 class="text-center mb-3">Most Sold Product</h4>
  <div class="container mt-3 d-flex justify-content-center">
    <div class="card text-center" style="max-width: 18rem;">
      <% if @most_sold_product.photo.attached? %>
        <%= image_tag @most_sold_product.photo, class: "card-img-top", alt: "Product Image", style: "max-height: 200px; object-fit: contain;" %>
      <% else %>
        <p>No Image Available</p>
      <% end %>
      <div class="card-body">
        <h5 class="card-title"><%= @most_sold_product.name %></h5>
        <p class="card-text"><%= @most_sold_product.description %></p>
        <p class="card-text">Price: <%= number_to_currency(@most_sold_product.price, unit: '$', precision: 2) %></p>
      </div>
    </div>
  </div>
<% end %>

<p class='fs-5 text-center mb-4'>Number of Sells: <%= @sell_count %></p>
<div class='container d-flex justify-content-between flex-wrap gap-2' style='margin-right: auto; margin-left: auto;'>
  <% @sells.each do |sell| %>
    <div class="card col-3">
      <p class='text-center fs-5'>Sell #<%= sell.id %></p>
      <div class="card-body">
        <% sell.products.each do |product| %>
          <div>
            <%= product.name %>
          </div>
        <% end %>
        <p class="card-text">Total Price: <%= number_to_currency(sell.total_price, unit: '$', precision: 2) %></p>
        <p class="card-text">Date: <%= sell.created_at.strftime('%Y-%m-%d') %></p>
        <p class="card-text">Hour: <%= sell.created_at.strftime('%H:%M:%S') %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/sells/new.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h1 class="text-center mb-4">Make a new sell</h1>

      <%= simple_form_for(@sell, url: sells_path) do |f| %>
        <%= f.hidden_field :user_id, value: current_user.id %>

        <div class="form-group">
          <%= label_tag 'products', 'Products', class: 'fs-4 mt-1 mb-1' %>
          <%= select_tag 'sell[product_ids][]', options_for_select(Product.all.map { |product| [product.name, product.id] }), class: 'fs-4 mt-2 mb-3 p-1 slim-select', data: { controller: 'selectable' }, multiple: true %>
        </div>

        <div class="text-center">
          <%= f.submit 'Create Sell', class: 'btn btn-success' %>
          <%= link_to "Cancel", sells_path(@sell), class: "btn btn-danger ml-2" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/sells/show.html.erb
<div class="container mt-5" data-controller="hello">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">
          <h2 class="text-center">Sell Details</h2>
        </div>
        <% if @sell %>
          <div class="card-body" id="print" data-sell-id="<%= @sell.id %>">
            <h6 class="card-title">
              <%= "Sell ID: #{@sell.id}" %><br>
              <% total_sell_price = @sell.products.sum(&:price) %>
              <% @sell.products.each do |product| %>
                <%= "#{product.name.capitalize} - $#{product.price}" %><br>
              <% end %>
              <p>Total Sell Price: <%= number_to_currency(total_sell_price, unit: '$', precision: 2) %></p>
            </h6>
            <p class="card-text">
              <span class="float-left">
                <% if @sell.created_at.present? %>
                  Comprado el: <%= @sell.created_at.strftime('%Y-%m-%d %H:%M:%S') %>
                <% else %>
                  Comprado el: N/A
                <% end %>
              </span>
            </p>
          </div>
        <% else %>
          <div class="card-body">
            <p class="card-text">Sell not found.</p>
          </div>
        <% end %>
        <div class="card-footer text-center">
          <button data-action="click->hello#generatePDF" class="btn btn-primary">Download PDF</button>
        </div>
      </div>
      <div class='container'>
        <%= link_to products_path, class: 'btn btn-success mt-2 text-center' do %>
          <i class="fas fa-cart-arrow-down"></i> Back to List
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lorenzo ">
  <div class="container-fluid">
    <%= link_to sells_path, class: "navbar-brand" do %>
    <%= image_tag "bee.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", sells_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Product List", products_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Register a sell", new_sell_path, class: "nav-link" %>
          </li>
          <li class="nav-item ">
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>